ChatterBox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('apps.chatterbox_app.urls')),
]

apps/chatterbox_app/urls.py
# chatterbox_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from . import views
from allauth.account.views import LoginView, LogoutView, PasswordChangeView, ConfirmEmailView

app_name = 'chatterbox_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('my_account/', views.my_account, name='my_account'),
    path('contacts/', views.contact_list, name='contact_list'),
    path('contact/new/', views.contact_create, name='contact_create'),
    path('contact/<int:pk>/delete/', views.contact_delete, name='contact_delete'),
    path('contact/<int:pk>/edit/', views.contact_update, name='contact_update'),
    path('email/inbox/', views.email_inbox, name='email_inbox'),
    path('email/inbox/load/', views.load_emails, name='load_emails'),
    path('email/inbox/<str:email_uid>/', views.email_detail, name='email_detail'),
    path('contact/<str:contact_id>/email/', views.send_email, name='send_email'),
    path('email/<str:email_address>/send/', views.send_email, name='send_email_address'),
    path('contact/<int:pk>/', views.ContactDetailView.as_view(), name='contact_detail'),
    path('contact/<int:pk>/add_note/', views.add_note, name='add_note'),
    path('contact/<int:contact_pk>/note/<int:pk>/edit/', views.note_edit, name='note_edit'),
    path('contact/<int:contact_pk>/note/<int:pk>/delete/', views.note_delete, name='note_delete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/chatterbox_app/models.py
# chatterbox_app/models.py

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# User model
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birthdate = models.DateField(null=True, blank=True)

    # Personal email
    smtp_email = models.EmailField(blank=True, null=True)
    smtp_password = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.user.username if self.user else 'No User'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# Contact
class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)  # New field

    def __str__(self):
        return f'{self.first_name} {self.last_name}' if self.first_name or self.last_name else self.email

# Note
class Note(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='contact_notes')
    note_content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)  # Added this line
    updated_at = models.DateTimeField(auto_now=True)  # Added this line

    def __str__(self):
        return f'{self.contact.first_name} {self.contact.last_name}: {self.note_content[:20]}...'


# Email
class Email(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='emails')
    subject = models.CharField(max_length=200)
    sender = models.EmailField()
    recipient = models.EmailField()
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject
    

apps/chatterbox_app/forms.py
# chatterbox_app/forms.py

from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Contact, Note


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
    username = forms.CharField(max_length=30, label='Username')
    phone_number = forms.CharField(max_length=20, label='Phone Number')

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        user.save()

        # Manually create the profile if it doesn't exist.
        Profile.objects.get_or_create(user=user, defaults={'phone_number': self.cleaned_data['phone_number']})

        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']
        widgets = {
            'username': forms.TextInput(attrs={'maxlength': 100}),
        }

class ProfileUpdateForm(forms.ModelForm):
    smtp_password = forms.CharField(widget=forms.PasswordInput, required=False)

    class Meta:
        model = Profile
        fields = ['phone_number', 'address', 'notes', 'bio', 'location', 'birthdate', 'smtp_email', 'smtp_password']

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'notes']


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['note_content', 'contact']  # 'content' changed to 'note_content'
        widgets = {'contact': forms.HiddenInput()}  # make 'contact' field hidden

apps/chatterbox_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse
from django.core.cache import cache
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import smtplib
import imaplib
from email import message_from_bytes
from smtplib import SMTPAuthenticationError
from datetime import timezone
from django.contrib import messages
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .forms import UserUpdateForm, ProfileUpdateForm, ContactForm, EmailForm, NoteForm
from .models import Contact, Note
from .utils import get_body, parse_email_date, fetch_emails, connect_smtp_server, connect_imap_server


def home(request):
    return render(request, 'chatterbox_app/home.html')


@login_required
def my_account(request):
    user = request.user
    profile = user.profile

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = ProfileUpdateForm(request.POST, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            smtp_password = profile_form.cleaned_data.get('smtp_password')
            if smtp_password:  # Check if the user provided a new password
                profile.smtp_password = smtp_password

            profile.save()
    else:
        user_form = UserUpdateForm(instance=user)
        profile_form = ProfileUpdateForm(instance=profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'chatterbox_app/my_account.html', context)


# Contact Views
@login_required
def contact_list(request):
    contacts = Contact.objects.filter(user=request.user)
    return render(request, 'chatterbox_app/contact_list.html', {'contacts': contacts})


@login_required
def contact_create(request):
    initial_data = {}
    if request.method == 'GET':
        email = request.GET.get('email')
        if email:
            initial_data['email'] = email

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect('chatterbox_app:contact_list')
    else:
        form = ContactForm(initial=initial_data)

    return render(request, 'chatterbox_app/contact_form.html', {'form': form})


@login_required
def contact_delete(request, pk):
    contact = get_object_or_404(Contact, pk=pk, user=request.user)

    if request.method == 'POST':
        contact.delete()
        return redirect('chatterbox_app:contact_list')

    return render(request, 'chatterbox_app/contact_confirm_delete.html', {'contact': contact})


@login_required
def contact_update(request, pk):
    contact = get_object_or_404(Contact, pk=pk, user=request.user)
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect('chatterbox_app:contact_list')
    else:
        form = ContactForm(instance=contact)

    return render(request, 'chatterbox_app/contact_form.html', {'form': form})


@login_required
def send_email(request, contact_id=None, email_address=None):
    if contact_id:
        contact = get_object_or_404(Contact, id=contact_id, user=request.user)
        recipient_email = contact.email
    elif email_address:
        recipient_email = email_address
        subject = request.GET.get('subject', '')
        message_id = request.GET.get('message_id', '')
    else:
        messages.error(request, 'No recipient specified.')
        return redirect('chatterbox_app:contact_list')

    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            smtp_email = request.user.profile.smtp_email
            smtp_password = request.user.profile.smtp_password

            msg = MIMEMultipart()
            msg['From'] = smtp_email
            msg['To'] = recipient_email
            msg['Subject'] = subject
            msg['In-Reply-To'] = message_id  # Set the 'In-Reply-To' header using the message_id variable
            msg.attach(MIMEText(message, 'plain'))

            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            try:
                server.login(smtp_email, smtp_password)
            except SMTPAuthenticationError:
                messages.error(
                    request, 'SMTP Authentication failed. Please check your SMTP username and password.')
                # Redirect them back to the account page to fix their SMTP settings.
                return redirect('chatterbox_app:my_account')

            text = msg.as_string()
            server.sendmail(smtp_email, recipient_email, text)
            server.quit()
            return redirect('chatterbox_app:contact_list')
    else:
        form = EmailForm(initial={'subject': subject})

    context = {
        'form': form,
        'recipient_email': recipient_email,
    }
    return render(request, 'chatterbox_app/email_form.html', context)


@login_required
def note_create(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id, user=request.user)
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.contact = contact
            note.save()
            return redirect('chatterbox_app:contact_detail', contact.id)
    else:
        form = NoteForm()
    return render(request, 'chatterbox_app/note_form.html', {'form': form, 'contact': contact})


class ContactDetailView(LoginRequiredMixin, DetailView):
    model = Contact
    template_name = 'chatterbox_app/contact_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notes'] = self.object.contact_notes.all()
        return context


@login_required
def add_note(request, pk):
    contact = get_object_or_404(Contact, pk=pk)

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.contact = contact
            note.save()
            return redirect('chatterbox_app:contact_detail', pk=contact.pk)
    else:
        form = NoteForm(initial={'contact': contact})

    return render(request, 'chatterbox_app/add_note.html', {'form': form})


@login_required
def note_edit(request, contact_pk, pk):
    note = get_object_or_404(Note, pk=pk, contact__user=request.user)

    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('chatterbox_app:contact_detail', pk=contact_pk)
    else:
        form = NoteForm(instance=note)

    return render(request, 'chatterbox_app/note_form.html', {'form': form})


@login_required
def note_delete(request, contact_pk, pk):
    note = get_object_or_404(Note, pk=pk, contact__user=request.user)

    if request.method == 'POST':
        note.delete()
        return redirect('chatterbox_app:contact_detail', pk=contact_pk)

    return render(request, 'chatterbox_app/note_confirm_delete.html', {'note': note})


@login_required
def email_inbox(request):
    user = request.user
    smtp_email = user.profile.smtp_email
    smtp_password = user.profile.smtp_password

    cache_key = f'email_inbox:{user.id}'
    emails = cache.get(cache_key)

    if emails is None:
        try:
            smtp_server = connect_smtp_server(smtp_email, smtp_password)
            emails = fetch_emails(user, -30, None)
            smtp_server.quit()
        except (smtplib.SMTPAuthenticationError, imaplib.IMAP4.error):
            messages.error(
                request, 'Failed to retrieve emails. Please check your SMTP username and password.')

        cache.set(cache_key, emails, 300)

    emails.sort(key=lambda e: parse_email_date(e[1]), reverse=True)
    paginator = Paginator(emails, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'chatterbox_app/email_inbox.html', context)


@login_required
def load_emails(request):
    user = request.user
    smtp_email = user.profile.smtp_email
    smtp_password = user.profile.smtp_password

    try:
        smtp_server = connect_smtp_server(smtp_email, smtp_password)
        cache_key = f'email_inbox:{user.id}'
        existing_emails = cache.get(cache_key, [])
        num_existing_emails = len(existing_emails)
        total_num_emails = len(fetch_emails(user, None, None))
        start_index = total_num_emails - num_existing_emails - 30
        end_index = start_index + 30
        new_emails = fetch_emails(user, start_index, end_index)
        smtp_server.quit()
    except (smtplib.SMTPAuthenticationError, imaplib.IMAP4.error):
        messages.error(
            request, 'Failed to retrieve emails. Please check your SMTP username and password.')

    all_emails = existing_emails + new_emails
    cache.set(cache_key, all_emails, 300)
    current_page_number = len(all_emails) // 10 + 1

    return redirect(reverse('chatterbox_app:email_inbox') + f'?page={current_page_number - 2}')


@login_required
def email_detail(request, email_uid):
    user = request.user
    smtp_email = user.profile.smtp_email
    smtp_password = user.profile.smtp_password

    try:

apps/chatterbox_app/templates/chatterbox_app/add_note.html
{% extends "chatterbox_app/base.html" %}

{% block content %}
  <h2>Add a note</h2>
  <form method="POST">
    {% csrf_token %}
    <div class="flex flex-col mb-4">
      {{ form.as_p }}
    </div>
    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">Add note</button>
  </form>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/base.html
{% load livereload_tags %}
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChatterBox</title>
    {% tailwind_css %}
</head>

<body class="bg-gray-100">
    <header class="bg-blue-500 text-white py-4">
        <div class="container mx-auto">
            <h1 class="text-2xl font-bold mb-2">ChatterBox</h1>
            <nav class="space-x-4">
                <a class="hover:text-blue-300" href="{% url 'chatterbox_app:home' %}">Home</a>
                {% if user.is_authenticated %}
                <a class="hover:text-blue-300" href="{% url 'chatterbox_app:my_account' %}">My Account</a>
                <a class="hover:text-blue-300" href="{% url 'chatterbox_app:contact_list' %}">Contacts</a>
                <a class="hover:text-blue-300" href="{% url 'chatterbox_app:email_inbox' %}">Emails</a>
                <a class="hover:text-blue-300" href="{% url 'account_logout' %}">Logout</a>
                {% else %}
                <a class="hover:text-blue-300" href="{% url 'account_login' %}">Login</a>
                <a class="hover:text-blue-300" href="{% url 'account_signup' %}">Sign Up</a>
                {% endif %}
            </nav>
        </div>
        {% if messages %}
        <ul class="messages container mx-auto mt-4">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </header>
    <main class="container mx-auto mt-8">
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

apps/chatterbox_app/templates/chatterbox_app/contact_confirm_delete.html
<!-- templates/chatterbox_app/contact_confirm_delete.html -->
{% extends "chatterbox_app/base.html" %}

{% block content %}
  <h2>Delete Contact</h2>
  <p>Are you sure you want to delete the contact "{{ contact.first_name }} {{ contact.last_name }}"?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/contact_detail.html
{% extends "chatterbox_app/base.html" %}

{% block content %}
  <h2 class="text-2xl font-semibold mb-4">Contact: {{ object.first_name }} {{ object.last_name }}</h2>
  <div class="bg-white p-4 rounded shadow">
    <p>Email: {{ object.email }}</p>
    <p>Phone: {{ object.phone }}</p>
  </div>

  <h3 class="text-xl font-semibold mt-8 mb-4">Notes:</h3>
  <ul class="space-y-4">
    {% for note in notes %}
    <li class="bg-white p-4 rounded shadow">
      <p>Date: {{ note.date }} | Created: {{ note.created_at }} | Last updated: {{ note.updated_at }}</p>
      <p>Note: {{ note.note_content }}</p>
      <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:note_edit' contact_pk=object.pk pk=note.pk %}">Edit</a>
      <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:note_delete' contact_pk=object.pk pk=note.pk %}">Delete</a>
    </li>
    {% empty %}
    <li>No notes yet.</li>
    {% endfor %}
  </ul>
  <div class="mt-4">
    <a class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700 inline-block" href="{% url 'chatterbox_app:contact_delete' pk=object.pk %}">Delete Contact</a>
    <a class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700 ml-2 inline-block" href="{% url 'chatterbox_app:add_note' pk=object.pk %}">Add Note</a>
  </div>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/contact_form.html
<!-- chatterbox_app/templates/chatterbox_app/contact_form.html -->
{% extends "chatterbox_app/base.html" %}

{% block content %}
    <h1>Add/Edit Contact</h1>
    <form method="post">
        {% csrf_token %}
        <div class="flex flex-col mb-4">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">Save</button>
    </form>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/contact_list.html
{% extends "chatterbox_app/base.html" %}

{% block content %}
<h2 class="text-2xl font-semibold mb-4">Contact List</h2>
<a class="bg-blue-500 text-white px-6 py-2 rounded hover:bg-blue-700 mb-4 inline-block" href="{% url 'chatterbox_app:contact_create' %}">Add Contact</a>
{% if contacts %}
<table class="table-auto w-full">
  <thead>
    <tr>
      <th class="border px-4 py-2">Name</th>
      <th class="border px-4 py-2">Email</th>
      <th class="border px-4 py-2">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for contact in contacts %}
    <tr>
      <td class="border px-4 py-2 text-center">{{ contact.first_name }} {{ contact.last_name }}</td>
      <td class="border px-4 py-2 text-center">{{ contact.email }}</td>
      <td class="border px-4 py-2 text-center">
        <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:contact_detail' pk=contact.pk %}">View</a> |
        <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:contact_update' pk=contact.pk %}">Edit</a> |
        <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:add_note' pk=contact.pk %}">Add Note</a> |
        <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:send_email' contact.id %}">Send Email</a> |
        <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:contact_delete' pk=contact.pk %}">Delete</a>
    </td>
    
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No contacts yet.</p>
{% endif %}
<a class="bg-blue-500 text-white px-6 py-2 rounded hover:bg-blue-700 mt-4 inline-block" href="{% url 'chatterbox_app:contact_create' %}">Add Contact</a>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/email_detail.html
{% extends 'chatterbox_app/base.html' %}
{% load custom_tags %}

{% block content %}
  <h2 class="text-black text-2xl font-semibold mb-4">Email Detail</h2>
  <div class="text-black bg-white p-4 rounded shadow">
    <strong>From:</strong> {{ email.From }}<br />
    <strong>Subject:</strong> {{ email.subject|decode_subject }}<br />
    <strong>Date:</strong> {{ email.Date }}<br />
    <strong>Message:</strong> {{ body|safe }}<br />
  </div>
  <div class="mt-4">
    <a class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700 inline-block" href="{% url 'chatterbox_app:send_email_address' email_address=email.From|parse_email_address %}?subject={{ email.subject|decode_subject|urlencode }}">Reply</a>
    <a class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700 ml-2 inline-block" href="{% url 'chatterbox_app:contact_create' %}?email={{ email.From|parse_email_address }}">Add Contact</a>
  </div>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/email_form.html
{% extends "chatterbox_app/base.html" %}

{% block content %}
    <h2 class="text-2xl font-semibold mb-4">Send Email</h2>
    <form method="post" class="bg-white p-4 rounded shadow">
        {% csrf_token %}
        <div class="flex flex-col mb-4">
            {{ form.as_p }}
        </div>
        <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700" type="submit">Send</button>
    </form>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/email_inbox.html
{% extends 'chatterbox_app/base.html' %}
{% load custom_tags %}

{% block content %}
  <h2 class="text-2xl font-semibold mb-4">Email Inbox</h2>
  <div class="mt-4">
    {% if page_obj.has_previous %}
      <a class="text-blue-500 hover:text-blue-700" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    {% if page_obj.has_next %}
      <a class="text-blue-500 hover:text-blue-700" href="?page={{ page_obj.next_page_number }}">Next</a>
    {% else %}
      <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:load_emails' %}">Load More</a>
    {% endif %}
  </div>
  {% if page_obj %}
    <ul class="space-y-4">
      {% for uid, email in page_obj %}
      <li class="bg-white p-4 rounded shadow hover:bg-gray-100 transition duration-300">
        <a class="grid grid-cols-3 gap-4 items-center justify-between" href="{% url 'chatterbox_app:email_detail' uid %}" role="listitem" aria-label="View Email">
          <div class="col-span-2 grid grid-cols-3 gap-4">
            <span class="col-span-1"><strong>From:</strong> {{ email.From }}</span>
            <span class="col-span-1"><strong>Subject:</strong> {{ email.subject|decode_subject }}</span>
            <span class="col-span-1"><strong>Date:</strong> {{ email.Date }}</span>
          </div>
          <span class="text-blue-500 hover:text-blue-700 col-span-1 text-right" tabindex="-1">View Email</span>
          <span class="text-blue-500 hover:text-blue-700 col-span-1 text-right" tabindex="-2">         
            <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:send_email_address' email_address=email.From|parse_email_address %}?subject={{ email.subject|decode_subject|urlencode }}">Reply</a>             
          </span>
          <span class="text-blue-500 hover:text-blue-700 col-span-1 text-right" tabindex="-3">             
            <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:contact_create' %}?email={{ email.From|parse_email_address }}">Add Contact</a>
          </span>

        </a>
        <div class="mt-2 flex flex-col">
          
        </div>
        <hr />
      </li>
      {% endfor %}    
    </ul>
    <div class="mb-4">
        {% if page_obj.has_previous %}
          <a class="text-blue-500 hover:text-blue-700" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% if page_obj.has_next %}
          <a class="text-blue-500 hover:text-blue-700" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% else %}
          <a class="text-blue-500 hover:text-blue-700" href="{% url 'chatterbox_app:load_emails' %}">Load More</a>
        {% endif %}
    </div>
  {% else %}
    <p>No emails found.</p>
  {% endif %}
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/home.html
{% extends 'chatterbox_app/base.html' %}
{% load custom_tags %}

{% block content %}
    <h2 class="text-2xl font-semibold mb-4">Welcome to ChatterBox!</h2>
    {% if user.is_authenticated %}
        <p>Hello, {{ user.first_name|proper_case }}!</p>
    {% else %}
        <p>Please log in or sign up to join the conversation.</p>
    {% endif %}
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/note_confirm_delete.html
<!-- templates/chatterbox_app/note_confirm_delete.html -->
{% extends "chatterbox_app/base.html" %}

{% block content %}
  <h2>Delete Note</h2>
  <p>Are you sure you want to delete the note "{{ note.note_content }}"?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
{% endblock %}

apps/chatterbox_app/templates/chatterbox_app/note_form.html
{% extends "chatterbox_app/base.html" %}

{% block content %}
  <h2 class="text-2xl font-semibold mb-4">Edit note</h2>
  <form method="POST" class="bg-white p-4 rounded shadow">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700" type="submit">Save note</button>
  </form>
{% endblock %}